### ISSUE TITLE
How to config Enmasse in latest version 1.0?

### ISSUE THREAD

**Issue by alexjuchina** [eclipse/hono#1495]
Hi Sir, 
I can config enmasse connection parameters in helm/config/hono-adapter-****-vertx-config.yml files in version 0.9.
But in 1.0 version, I can't find this folder.
where can I config Enmasse host and account ?
Thanks.

**Comment by sophokles73** [comment]
In 1.0 we have replaced the yaml config files with Helm values which can be set in the `helm/values.yaml` file. You need to add the config properties to the `adapters/amqpMessagingNetworkSpec` and `adapters/commandAndControlSpec` properties, e.g.
```
# Configuration options for adapters.
adapters:
  amqpMessagingNetworkSpec:
    host: enmasse.mydomain.org
    port: 5672
    username: myuser
    password: mypwd
  commandAndControlSpec:
    host: enmasse.mydomain.org
    port: 5672
    username: myuser
    password: mypwd
```
