### ISSUE TITLE
Support Hono deployment in multi-tenant messaging environments

### ISSUE THREAD

**Issue by dejanb** [eclipse/hono#2070]
In multi-tenant messaging environments there could be different connection endpoints used by infrastructure and end users. For end users in this case, the addresses are usually translated internally in order to enable consistent namespaces.

For example, dispatch router enables this behaviour through the (poorly) documented `multiTenant` property

```
  ["listener", {
    "host": "0.0.0.0",
    "port": 5672,
    "linkCapacity": 100,
    "authenticatePeer": true,
    "saslMechanisms": "PLAIN",
    "saslPlugin": "Hono Auth",
    "multiTenant": true
  }]
```

When clients connect through a listener like this, all addresses in the attach frames will be prefixed with the virtual host prefix. e.g. `telemetry/DEFAULT_TENANT` would become `test-vhost/telemetry/DEFAULT_TENANT` internally. End clients are be unaware of this. There are more work being done in the router to make this more configurable in the future (mosly to support Kubernetes namespaces), but the basic principles will remain the same.

In order to be able to work in such environments, infrastructure components connecting through the non multi-tenant listeners and are responsible of doing address translation on thier own. The proposal is to add an option for protocol adapters to rewrite addresses when opening links to the AMQP network.
The idea is to provide a configuration option similar to popular web server URL rewrite rules.

The rule configuration would be in the `"$PATTERN $SUBSTITUTION"` format. The `$PATTERN` should match the original address. It uses the regular Java pattern syntax. There are two helper constants introduced:
	* `ENDPOINT` - that will match the current endpoint being used</li>
    * `ID` - a pattern that will match any identity (using default format) in the system

Example configuration could look like this:

```
  messaging:
    name: Hono adapter-http-vertx
    amqpHostname: hono-internal
    host: eclipse-hono-dispatch-router
    port: 5673
    keyPath: /etc/hono/key.pem
    certPath: /etc/hono/cert.pem
    trustStorePath: /etc/hono/trusted-certs.pem
    hostnameVerificationRequired: false
    addressRewriteRule: (${ENDPOINT})/(${ID}) test-vhost/$1/$2
  command:
    name: Hono adapter-http-vertx
    amqpHostname: hono-internal
    host: eclipse-hono-dispatch-router
    port: 5673
    keyPath: /etc/hono/key.pem
    certPath: /etc/hono/cert.pem
    trustStorePath: /etc/hono/trusted-certs.pem
    hostnameVerificationRequired: false
    addressRewriteRule: (${ENDPOINT})/(${ID}) test-vhost/$1/$2
```

This would result in aforementioned rewrites that prefix addresses with virtual host (`test-vhost`) in this example.
This feature is completely optional and doesn't affect the behaviour of the system if it's not used. If it's used it changes the contract between adapters and the AMQP network, but not for the devices and business applications.

A deployment that could be used to test this kind of setup could be found here:

Router config: https://github.com/dejanb/packages/blob/address-rewrite/charts/hono/config/router/qdrouterd-multitenant.json
Chart config file: https://github.com/dejanb/packages/blob/address-rewrite/charts/hono/addressRewrite.yaml

This could be added to the chart after the Hono properly supports this feature.
