### ISSUE TITLE
Device-ID and Tenant-ID validation regex configuration option not working

### ISSUE THREAD

**Issue by akofoed** [eclipse/hono#2217]
According to the documentation in [file-based](https://www.eclipse.org/hono/docs/admin-guide/file-based-device-registry-config/) or [Mongo-based](https://www.eclipse.org/hono/docs/admin-guide/mongodb-device-registry-config/) it should be possible to pass the command-line option HONO_REGISTRY_HTTP_DEVICE_ID_REGEX or set the option "hono.registry.http.deviceIdRegex" in the  application.yaml. This is not working. The same goes for Tenant-ID.
This can also be confirmed by searching for references to the method "setDeviceIdPattern()" in core/src/main/java/org/eclipse/hono/config/ServiceConfigProperties.java. [There are currently none](https://github.com/eclipse/hono/search?q=setDeviceIdPattern). Same goes for setTenantIdPattern().

#2201 might be affected/related to this.

**Comment by sophokles73** [comment]
The `hono.registry.http.*` properties are available since Hono 1.4.0. They are replacing the corresponding properties with the `hono.registry.rest` prefix. The new prefix is used, if no properties with the `hono.registry.rest` prefix are set. Can you check if you are setting any of the following properties:
* `hono.registry.rest.keyPath`
* `hono.registry.rest.keyStorePath`
* `hono.registry.rest.insecurePortEnabled`
* `hono.registry.rest.insecurePort`
* `hono.registry.rest.insecurePortBindAddress`

If you do, then you should either migrate them to the new prefix or set the patterns using the old prefix as well.

**Comment by calohmn** [comment]
> This can also be confirmed by searching for references to the method "setDeviceIdPattern()" in core/src/main/java/org/eclipse/hono/config/ServiceConfigProperties.java. There are currently none. Same goes for setTenantIdPattern().

These setter methods are generally not called directly in the code as the property objects get populated via Spring Boot.

**Comment by akofoed** [comment]
Thanks for you reply.
I am using 1.4.0 and are using the hono.registry.http config options. This is my application.yml:

```
hono:
  app:
    maxInstances: 1
    startupTimeout: 90
  healthCheck:
    insecurePortBindAddress: 0.0.0.0
    insecurePort: 8088
  auth:
    host: hono-service-auth.hono
    port: 5672
    name: device-registry
    validation:
      certPath: /etc/hono/certs/auth-server-cert.pem
  registry:
    amqp:
      insecurePortEnabled: true
      insecurePortBindAddress: 0.0.0.0
    http:
      authenticationRequired: false
      insecurePortEnabled: true
      insecurePortBindAddress: 0.0.0.0
      deviceIdRegex: ^[a-zA-Z0-9-_\.:]++$
    svc:
  credentials:
    svc:
      maxBcryptIterations: 4
  tenant:
    svc:
  mongodb:
    host: hono-mongodb.hono
    port: 27017
    dbName: hono
    username: device-registry@HONO
    password: device-registry-secret
  vertx:
    maxEventLoopExecuteTime: 5000

spring:
  jmx:
    enabled: false

management:
  port: -1

server:
  port: -1
```

When i try to create a new device with a namespace ID (eg. namespace:deviceID using HTTP POST (or get):
http://$REGISTRY_IP:28080/v1/devices/$MY_TENANT/namespace:deviceID

I get a 400 Bad Request:
`request parameter [name: device_id, value: namespace:deviceID] failed validation: value does not match pattern [^[a-zA-Z0-9-_\.]++$]`

It is clear that it does not pick up the deviceIdRegex.

As @calohmn suggested, I had a look at the wiring, and the class [HttpServiceConfigProperties](https://github.com/eclipse/hono/search?q=HttpServiceConfigProperties), referenced by `@ConfigurationProperties(prefix = "hono.registry.http")
` does not contain anything that looks like something that can set the deviceIDPattern or call the setter setDeviceIdPattern().

Same for tenantIdPattern.

Let me know if there is anything I can do to help.
Kind regards
Anders
