### ISSUE TITLE
JDBC device registry tables creation.

### ISSUE THREAD

**Issue by kramarov666** [eclipse/hono#2407]
Hi, I'm trying to create tables for device registry. In Postgresql database.
I'm creating them manually in pgadmin4  using these scripts:
https://github.com/eclipse/hono/tree/master/services/base-jdbc/src/main/sql/postgresql
Then I'm trying to create tenant and device using these commands:
```
curl -i -X POST http://device-registry:8080/v1/tenants
```
```
curl -i -X POST http://device-registry:8080/v1/devices/7bbd39ef-67ec-48a3-9ef7-e9a2f7e257fa/test1921038103
```
Tenant creation went fine, but device creation failing with error:
```
SQL Error: 07006: Can't infer the SQL type to use for an instance of java.time.Instant. Use setObject() with an explicit Types value to specify the type to use.
```
```
sql=INSERT INTO device_registrations (
   tenant_id,
   device_id,
   version,
   data,
   created,
   auto_provisioned
) VALUES (
   ?,
   ?,
   ?,
   ?::jsonb,
   ?,
   ?
)
```
I'm running ***Hono version 1.5.0***  deployed by Helm chart, inside Kubernetes cluster.
***Postgresql version: 11.10.0***
***index.docker.io/eclipse/hono-service-device-registry-jdbc:1.5.0***

Part of the Helm values, related to the jdbc:
```
 jdbcBasedDeviceRegistry:
    registry:
      jdbc:
        adapter: 
          url: jdbc:postgresql://hono-deviceregistry-postgresql/registry
          driverClass:  org.postgresql.Driver
          username: registry
          password: *
        management:
          url: jdbc:postgresql://hono-deviceregistry-postgresql/registry
          driverClass: org.postgresql.Driver
          username: registry
          password: *
    tenant:
      jdbc:
        adapter:
          url: jdbc:postgresql://hono-deviceregistry-postgresql/tenant
          driverClass: org.postgresql.Driver
          username: tenant
          password: *
        management:
          url: jdbc:postgresql://hono-deviceregistry-postgresql/tenant
          driverClass: org.postgresql.Driver
          username: tenant
          password: *
```
