### ISSUE TITLE
TlsEnable = false is not enough to disable TLS

### ISSUE THREAD

**Issue by BobClaerhout** [eclipse/hono#2538]
Since https://github.com/eclipse/packages/commit/3f6f58873d18c71c35844a0c3167da17710b2745 you have one additional config to make to disable TLS.
Setting tlsEnabled to false in the AmqpMessagingNetworkSpec is not enough, you have to set to clear trustStorepath as well:
```
    amqpMessagingNetworkSpec:
      host: host
      port: 5672
      keyPath: /etc/hono/key.pem
      certPath: /etc/hono/cert.pem
      trustStorePath: 
      username: username
      password: password
      tlsEnabled: false
```
Otherwise, this line of code enables the tls again:
https://github.com/eclipse/hono/blob/1bc3764acfeb667e9f41087660ea0b84741c53b4/core/src/main/java/org/eclipse/hono/config/AuthenticatingClientConfigProperties.java#L275
I think this is very counter intuitive. The tlsEnabled flag is not documented at all and neither is the fact that this is silently enabled again because of the trustStorePath still being configure while you might not have that line there but just exists because it default to that value.
