### ISSUE TITLE
HotRod client connectionPool config can't be set in usual camel-case notation (Quarkus-based Command Router)

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#3106]
When configuring the connection pool properties for the HotRod client in a Quarkus-based Command Router component, I would have expected the configuration to look like this:
```
hono:
  commandRouter:
    cache:
      remote:
        connectionPoolMinIdle: 10
```
(this works for the spring-boot-based component)
or
```
[...]
        connectionPool:
          minIdle: 10
```
.

However, it only works with
```
[...]
        connectionPool:
          min_idle: 10
```

The snake-case notation here ("min_idle") looks unintuitive.

FMPOV, at least
```
[...]
        connectionPool:
          minIdle: 10
```
should be supported as well.
