### ISSUE TITLE
Mqtt Payload Size to 8kb

### ISSUE THREAD

**Issue by vishalk2203** [eclipse/hono#3124]
We're trying to set up a env variable to increase mqtt payload to 8kb in GKE Cluster . I'm setting up that values through values.yaml file. Still, our goal isn't achieved via this method. Please guide us with the right solution.

useLoadBalancer: true
prometheus:
  createInstance: false
grafana:
  enabled: false
deviceRegistryExample:
  enabled: true
  type: mongodb
mongodb:
  createInstance: true
  usePassword: true
  mongodbRootPassword: root-secret
  mongodbUsername: device-registry@HONO
  mongodbPassword: hono-secret
  mongodbDatabase: honodb
  useStatefulSet: true
  nameOverride: mongodb-server
  volumePermissions:
    enabled: false
jaegerBackendExample:
  enabled: false
adapters:
  mqtt:
    resources:
      requests:
        cpu: "500m"
        memory: "900Mi"
      limits:
        cpu: "2"
        memory: "950Mi"
    hono:
      app:
        maxInstances: 2
**hono:
  mqtt:
    maxPayloadSize: 8192**

![logmqtt](https://user-images.githubusercontent.com/32649278/155841279-3dbbcc41-ce8d-40da-9dcb-47407bf74894.JPG)

**Comment by sophokles73** [comment]
Hi,
can you provide the formatted content of your values.yaml file and the command line that you are using to deploy Hono?

**Comment by vishalk2203** [comment]
`useLoadBalancer: true
prometheus:
  createInstance: false
grafana:
  enabled: false
deviceRegistryExample:
  enabled: true
  type: mongodb
mongodb:
  createInstance: true
  usePassword: true
  mongodbRootPassword: root-secret
  mongodbUsername: device-registry@HONO
  mongodbPassword: hono-secret
  mongodbDatabase: honodb
  useStatefulSet: true
  nameOverride: mongodb-server
  volumePermissions:
    enabled: false
jaegerBackendExample:
  enabled: false
adapters:
  mqtt:
    resources:
      requests:
        cpu: "500m"
        memory: "900Mi"
      limits:
        cpu: "2"
        memory: "950Mi"
    hono:
      app:
        maxInstances: 2
hono:
  mqtt:
    maxPayloadSize: 8192
  service:
    maxPayloadSize: 8192
`

**Comment by vishalk2203** [comment]
useLoadBalancer: true
prometheus:
  createInstance: false
grafana:
  enabled: false
deviceRegistryExample:
  enabled: true
  type: mongodb
mongodb:
  createInstance: true
  usePassword: true
  mongodbRootPassword: root-secret
  mongodbUsername: device-registry@HONO
  mongodbPassword: hono-secret
  mongodbDatabase: honodb
  useStatefulSet: true
  nameOverride: mongodb-server
  volumePermissions:
    enabled: false
jaegerBackendExample:
  enabled: false
adapters:
  mqtt:
    resources:
      requests:
        cpu: "500m"
        memory: "900Mi"
      limits:
        cpu: "2"
        memory: "950Mi"
    hono:
      app:
        maxInstances: 2
hono:
  mqtt:
    maxPayloadSize: 8192
  service:
    maxPayloadSize: 8192

**Comment by vishalk2203** [comment]
``

**Comment by vishalk2203** [comment]
![image](https://user-images.githubusercontent.com/32649278/155955046-cc476579-fe18-4f1e-b7c9-c2dd7575ce31.png)

**Comment by vishalk2203** [comment]
![image](https://user-images.githubusercontent.com/32649278/155955144-218c1bee-5529-4acd-837a-20000f37d6c1.png)

**Comment by vishalk2203** [comment]
I'm using gloud CLI.

**Comment by sophokles73** [comment]
> I'm using gloud CLI.

What is that supposed to mean? Can you paste the command that you use to deploy Hono?

**Comment by vishalk2203** [comment]
> What is that supposed to mean? Can you paste the command that you use to deploy Hono?
Im using helm command to install hono in kubernetes cluster.

helm install my-hono eclipse-iot/hono -f values.yaml --version 1.10.17 -n hono

**Comment by sophokles73** [comment]
Is there a particular reason why you want to use such an old version of the chart? You should try to use the most recent one.
Anyway, the Helm chart does not provide a separate property for changing an adapter's max payload size. However, you can use the *adapters.mqtt.hono.mqtt* property to provide *all* the MQTT adapter's (required/needed) configuration properties having the `hono.mqtt.` prefix. In your case, this would mean to include in your values.yaml:

```yaml
adapters:
  mqtt:
    resources:
      requests:
        cpu: "500m"
        memory: "900Mi"
      limits:
        cpu: "2"
        memory: "950Mi"
      hono:
        app:
          maxInstances: 2
        mqtt:
          bindAddress: "0.0.0.0"
          insecurePortBindAddress: "0.0.0.0"
          insecurePortEnabled: true
          keyPath: "/etc/hono/key.pem"
          certPath: "/etc/hono/cert.pem"
          tenantIdleTimeout: "1h"
          maxPayloadSize: 8192
```
